# Generated by Django 5.0.6 on 2024-06-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0003_playbooklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
    ]
