---
- name: Test playbook
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Display message
      debug:
        msg: "This is a test message."
        
    - name: Display message
      debug:
        msg: "{{ test_var }}"

    - name: Display message
      debug:
        msg: "{{ var2 }}"

    - name: Display message
      debug:
        msg: "{{ password_var }}"

    - name: Display IP address
      debug:
        msg: "IP address is {{ ansible_default_ipv4.address }}"
