---
- name: Test playbook
  hosts: localhost
  vars_files:
    - ../var/display_msg_cbs_vars.yml
  tasks:
    - name: Display message
      debug:
        msg: "This is a test message."
    - name: Display message
      debug:
        msg: "{{ test_var }}"
    - name: Display message
      debug:
        msg: "{{ var2 }}"
    - name: Display message
      debug:
        msg: "{{ var3 }}"
